<a href="https://colab.research.google.com/github/renadkassem923-collab/Network-Infrastructure-Cisco-Packet-Tracer/blob/main/Qubeterra_Theme4_Data_Collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Qubeterra AI NextGen - Theme 4")
print("Data Collection Phase")

Qubeterra AI NextGen - Theme 4
Data Collection Phase

In [4]:
import pandas as pd

df = pd.read_excel('/content/transformer_60_papers_research.xlsx')

df.head()

,paper_id,title,authors,year,debate_topic,method,paper_url,discovery_sources,research_note,source_type
0,P001,Sparsely-Gated Mixture-of-Experts,Noam Shazeer et al.,2017,MoE vs Dense,MoE,https://arxiv.org/abs/1701.06538,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
1,P002,Outrageously Large Neural Networks: The Sparse...,Noam Shazeer et al.,2017,MoE vs Dense,MoE,https://arxiv.org/abs/1701.06538,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
2,P003,Switch Transformers: Scaling to Trillion Param...,William Fedus et al.,2021,MoE vs Dense,MoE,https://arxiv.org/abs/2101.03961,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
3,P004,GLaM: Efficient Scaling of Language Models wit...,Du et al.,2021,MoE vs Dense,MoE,https://arxiv.org/abs/2112.06905,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
4,P005,ST-MoE: Designing Stable and Transferable Spar...,Barret Zoph et al.,2022,MoE vs Dense,MoE,https://arxiv.org/abs/2202.08906,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index

In [5]:
print("Number of papers:", len(df))
print(df.columns.tolist())

Number of papers: 60
['paper_id', 'title', 'authors', 'year', 'debate_topic', 'method', 'paper_url', 'discovery_sources', 'research_note', 'source_type']

In [6]:
df.head(5)

,paper_id,title,authors,year,debate_topic,method,paper_url,discovery_sources,research_note,source_type
0,P001,Sparsely-Gated Mixture-of-Experts,Noam Shazeer et al.,2017,MoE vs Dense,MoE,https://arxiv.org/abs/1701.06538,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
1,P002,Outrageously Large Neural Networks: The Sparse...,Noam Shazeer et al.,2017,MoE vs Dense,MoE,https://arxiv.org/abs/1701.06538,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
2,P003,Switch Transformers: Scaling to Trillion Param...,William Fedus et al.,2021,MoE vs Dense,MoE,https://arxiv.org/abs/2101.03961,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
3,P004,GLaM: Efficient Scaling of Language Models wit...,Du et al.,2021,MoE vs Dense,MoE,https://arxiv.org/abs/2112.06905,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index
4,P005,ST-MoE: Designing Stable and Transferable Spar...,Barret Zoph et al.,2022,MoE vs Dense,MoE,https://arxiv.org/abs/2202.08906,Hugging Face Papers; Semantic Scholar; Papers ...,Use the paper abstract/full text as the eviden...,Paper index

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   paper_id           60 non-null     object
 1   title              60 non-null     object
 2   authors            60 non-null     object
 3   year               60 non-null     int64
 4   debate_topic       60 non-null     object
 5   method             60 non-null     object
 6   paper_url          60 non-null     object
 7   discovery_sources  60 non-null     object
 8   research_note      60 non-null     object
 9   source_type        60 non-null     object
dtypes: int64(1), object(9)
memory usage: 4.8+ KB

In [8]:
df.isnull().sum()

paper_id             0
title                0
authors              0
year                 0
debate_topic         0
method               0
paper_url            0
discovery_sources    0
research_note        0
source_type          0
dtype: int64

In [9]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate paper IDs:", df["paper_id"].duplicated().sum())

Duplicate rows: 0
Duplicate paper IDs: 0

In [10]:
print(df["debate_topic"].value_counts())

debate_topic
MoE vs Dense                                  12
Normal vs Linear Attention vs SSM             10
Sliding Window / Local vs Global              10
Hybrid Architectures                          10
Pretraining vs Reasoning-Oriented Training    10
PPO vs GRPO                                    8
Name: count, dtype: int64

In [11]:
print(df["discovery_sources"].value_counts())

discovery_sources
Hugging Face Papers; Semantic Scholar; Papers With Code    60
Name: count, dtype: int64

In [12]:
df[["paper_id", "title", "year", "debate_topic", "method", "paper_url", "discovery_sources"]].head(10)

,paper_id,title,year,debate_topic,method,paper_url,discovery_sources
0,P001,Sparsely-Gated Mixture-of-Experts,2017,MoE vs Dense,MoE,https://arxiv.org/abs/1701.06538,Hugging Face Papers; Semantic Scholar; Papers ...
1,P002,Outrageously Large Neural Networks: The Sparse...,2017,MoE vs Dense,MoE,https://arxiv.org/abs/1701.06538,Hugging Face Papers; Semantic Scholar; Papers ...
2,P003,Switch Transformers: Scaling to Trillion Param...,2021,MoE vs Dense,MoE,https://arxiv.org/abs/2101.03961,Hugging Face Papers; Semantic Scholar; Papers ...
3,P004,GLaM: Efficient Scaling of Language Models wit...,2021,MoE vs Dense,MoE,https://arxiv.org/abs/2112.06905,Hugging Face Papers; Semantic Scholar; Papers ...
4,P005,ST-MoE: Designing Stable and Transferable Spar...,2022,MoE vs Dense,MoE,https://arxiv.org/abs/2202.08906,Hugging Face Papers; Semantic Scholar; Papers ...
5,P006,DeepSeekMoE: Towards Ultimate Expert Specializ...,2024,MoE vs Dense,MoE,https://arxiv.org/abs/2401.06066,Hugging Face Papers; Semantic Scholar; Papers ...
6,P007,Mixtral of Experts,2024,MoE vs Dense,MoE,https://arxiv.org/abs/2401.04088,Hugging Face Papers; Semantic Scholar; Papers ...
7,P008,DeepSpeed-MoE: Advancing Mixture-of-Experts In...,2022,MoE vs Dense,MoE systems,https://arxiv.org/abs/2201.05596,Hugging Face Papers; Semantic Scholar; Papers ...
8,P009,Expert Choice Routing Strategies for Mixture-o...,2022,MoE vs Dense,MoE routing,https://arxiv.org/abs/2202.09368,Hugging Face Papers; Semantic Scholar; Papers ...
9,P010,StableMoE: Stable Routing Strategy for Mixture...,2022,MoE vs Dense,MoE routing,https://arxiv.org/abs/2206.03382,Hugging Face Papers; Semantic Scholar; Papers ...

In [21]:
import requests

url = df["paper_url"].iloc[0]

response = requests.get(url, timeout=30)

print("Status:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))
print("Size:", len(response.content))

Status: 200
Content-Type: text/html; charset=utf-8
Size: 44764

In [13]:
import os

os.makedirs("papers_pdf", exist_ok=True)
os.makedirs("papers_text", exist_ok=True)
os.makedirs("papers_chunks", exist_ok=True)

print("Folders created successfully")

Folders created successfully

In [14]:
!pip -q install requests pymupdf

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 53.4 MB/s eta 0:00:00

In [15]:
import requests
import os
import time

def download_pdf(url, paper_id):
    try:
        response = requests.get(
            url,
            timeout=30,
            headers={"User-Agent": "Mozilla/5.0"}
        )

        if response.status_code == 200:
            path = f"papers_pdf/{paper_id}.pdf"

            with open(path, "wb") as f:
                f.write(response.content)

            return path

        return None

    except Exception as e:
        print(f"Error with {paper_id}: {e}")
        return None

In [16]:
downloaded = []

for _, row in df.iterrows():

    paper_id = row["paper_id"]
    url = row["paper_url"]

    path = download_pdf(url, paper_id)

    if path:
        downloaded.append(paper_id)

    time.sleep(1)

print("Downloaded:", len(downloaded))

Downloaded: 60

In [17]:
import os

os.makedirs("/content/papers", exist_ok=True)

In [20]:
import os

print(os.listdir("/content")[:30])

['.config', 'transformer_60_papers_research.xlsx', '.ipynb_checkpoints', 'papers_chunks', 'papers_text', 'papers', 'papers_pdf', 'sample_data']

In [22]:
import os

pdf_files = [
    f for f in os.listdir("papers_pdf")
    if f.lower().endswith(".pdf")
]

print("Number of PDFs:", len(pdf_files))
print(pdf_files[:10])

Number of PDFs: 60
['P019.pdf', 'P021.pdf', 'P028.pdf', 'P016.pdf', 'P030.pdf', 'P046.pdf', 'P014.pdf', 'P018.pdf', 'P047.pdf', 'P002.pdf']

In [23]:
import fitz

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

In [25]:
first_pdf = os.path.join("papers_pdf", pdf_files[0])

doc = fitz.open(first_pdf)

text = ""

for page in doc:
    text += page.get_text()

doc.close()

print(text[:3000])

Skip to main content
[image]
 Search Submit Donate Log in
Search arXiv
Press Enter to search · Advanced search
Computer Science > Machine
Learning
arXiv:2312.00752 (cs)
[Submitted on 1 Dec 2023 (v1), last revised 31 May 2024 (this
version, v2)]
Title:Mamba: Linear-Time
Sequence Modeling with
Selective State Spaces
Authors:Albert Gu, Tri Dao
View PDF HTML (experimental)
Abstract:Foundation models, now powering most of
the exciting applications in deep learning, are
almost universally based on the Transformer
architecture and its core attention module. Many
subquadratic-time architectures such as linear
attention, gated convolution and recurrent models,
and structured state space models (SSMs) have
been developed to address Transformers'
computational inefficiency on long sequences, but
they have not performed as well as attention on
important modalities such as language. We identify
that a key weakness of such models is their
inability to perform content-based reasoning, and
make several improvements. First, simply letting
the SSM parameters be functions of the input
addresses their weakness with discrete modalities,
allowing the model to selectively propagate or
forget information along the sequence length
dimension depending on the current token. Second,
even though this change prevents the use of
efficient convolutions, we design a hardware-aware
parallel algorithm in recurrent mode. We integrate
these selective SSMs into a simplified end-to-end
neural network architecture without attention or
even MLP blocks (Mamba). Mamba enjoys fast
inference (5$\times$ higher throughput than
Transformers) and linear scaling in sequence
length, and its performance improves on real data
up to million-length sequences. As a general
sequence model backbone, Mamba achieves state-
of-the-art performance across several modalities
such as language, audio, and genomics. On
language modeling, our Mamba-3B model
outperforms Transformers of the same size and
matches Transformers twice its size, both in
pretraining and downstream evaluation.
Subjects: Machine Learning (cs.LG); Artificial Intelligence (cs.AI)
Cite as:
arXiv:2312.00752 [cs.LG]

(or arXiv:2312.00752v2 [cs.LG] for this version)

https://doi.org/10.48550/arXiv.2312.00752
Focus to learn more
arXiv-issued DOI via DataCite
Submission history
From: Albert Gu [view email]
[v1] Fri, 1 Dec 2023 18:01:34 UTC (1,264 KB)
[v2] Fri, 31 May 2024 17:55:27 UTC (1,017 KB)
Full-text links:
Access Paper:
•  View PDF
•  HTML (experimental)
•  TeX Source
[image] view license
Current browse context:
cs.LG
< prev   |   next >
new | recent | 2023-12
Change to browse by:
cs
cs.AI
References & Citations
•  NASA ADS
•  Google Scholar
•  Semantic Scholar
2 blog links
(what is this?)
export BibTeX citation
BibTeX formatted citation
×
loading...
Data provided by:
Bookmark
[image] [image]
◉ Bibliographic Tools
Bibliographic and Citation
Tools
☐ Bibliographic Explorer Toggle
Bibliographic Explorer (What is the Explorer?)
☐ Connected P

In [26]:
texts = []

for pdf_file in pdf_files:

    pdf_path = os.path.join("papers_pdf", pdf_file)

    try:
        doc = fitz.open(pdf_path)

        text = ""

        for page in doc:
            text += page.get_text()

        doc.close()

        paper_id = os.path.splitext(pdf_file)[0]

        texts.append({
            "paper_id": paper_id,
            "text": text
        })

    except Exception as e:
        print("Error:", pdf_file, e)

print("Papers with extracted text:", len(texts))

Papers with extracted text: 60

In [27]:
import re

def clean_text(text):
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^\x00-\x7F]+", " ", text)
    return text.strip()

In [28]:
cleaned_texts = []

for item in texts:

    cleaned = clean_text(item["text"])

    cleaned_texts.append({
        "paper_id": item["paper_id"],
        "text": cleaned
    })

print("Cleaned papers:", len(cleaned_texts))

Cleaned papers: 60

In [29]:
print(cleaned_texts[0]["text"][:2000])

Skip to main content [image] Search Submit Donate Log in Search arXiv Press Enter to search   Advanced search Computer Science > Machine Learning arXiv:2312.00752 (cs) [Submitted on 1 Dec 2023 (v1), last revised 31 May 2024 (this version, v2)] Title:Mamba: Linear-Time Sequence Modeling with Selective State Spaces Authors:Albert Gu, Tri Dao View PDF HTML (experimental) Abstract:Foundation models, now powering most of the exciting applications in deep learning, are almost universally based on the Transformer architecture and its core attention module. Many subquadratic-time architectures such as linear attention, gated convolution and recurrent models, and structured state space models (SSMs) have been developed to address Transformers' computational inefficiency on long sequences, but they have not performed as well as attention on important modalities such as language. We identify that a key weakness of such models is their inability to perform content-based reasoning, and make several improvements. First, simply letting the SSM parameters be functions of the input addresses their weakness with discrete modalities, allowing the model to selectively propagate or forget information along the sequence length dimension depending on the current token. Second, even though this change prevents the use of efficient convolutions, we design a hardware-aware parallel algorithm in recurrent mode. We integrate these selective SSMs into a simplified end-to-end neural network architecture without attention or even MLP blocks (Mamba). Mamba enjoys fast inference (5$\times$ higher throughput than Transformers) and linear scaling in sequence length, and its performance improves on real data up to million-length sequences. As a general sequence model backbone, Mamba achieves state- of-the-art performance across several modalities such as language, audio, and genomics. On language modeling, our Mamba-3B model outperforms Transformers of the same size and matches Transformers twice its

In [30]:
print("Cleaned papers:", len(cleaned_texts))

Cleaned papers: 60

In [31]:
paper_metadata = df.set_index("paper_id").to_dict("index")

documents = []

for item in cleaned_texts:

    paper_id = item["paper_id"]

    if paper_id in paper_metadata:
        metadata = paper_metadata[paper_id]

        documents.append({
            "paper_id": paper_id,
            "title": metadata["title"],
            "authors": metadata["authors"],
            "year": metadata["year"],
            "debate_topic": metadata["debate_topic"],
            "method": metadata["method"],
            "source": metadata["discovery_sources"],
            "text": item["text"]
        })

print("Documents:", len(documents))

Documents: 60

In [32]:
print(documents[0])

{'paper_id': 'P019', 'title': 'Mamba: Linear-Time Sequence Modeling with Selective State Spaces', 'authors': 'Albert Gu, Tri Dao', 'year': 2023, 'debate_topic': 'Normal vs Linear Attention vs SSM', 'method': 'SSM / Mamba', 'source': 'Hugging Face Papers; Semantic Scholar; Papers With Code', 'text': "Skip to main content [image] Search Submit Donate Log in Search arXiv Press Enter to search   Advanced search Computer Science > Machine Learning arXiv:2312.00752 (cs) [Submitted on 1 Dec 2023 (v1), last revised 31 May 2024 (this version, v2)] Title:Mamba: Linear-Time Sequence Modeling with Selective State Spaces Authors:Albert Gu, Tri Dao View PDF HTML (experimental) Abstract:Foundation models, now powering most of the exciting applications in deep learning, are almost universally based on the Transformer architecture and its core attention module. Many subquadratic-time architectures such as linear attention, gated convolution and recurrent models, and structured state space models (SSMs) have been developed to address Transformers' computational inefficiency on long sequences, but they have not performed as well as attention on important modalities such as language. We identify that a key weakness of such models is their inability to perform content-based reasoning, and make several improvements. First, simply letting the SSM parameters be functions of the input addresses their weakness with discrete modalities, allowing the model to selectively propagate or forget information along the sequence length dimension depending on the current token. Second, even though this change prevents the use of efficient convolutions, we design a hardware-aware parallel algorithm in recurrent mode. We integrate these selective SSMs into a simplified end-to-end neural network architecture without attention or even MLP blocks (Mamba). Mamba enjoys fast inference (5$\\times$ higher throughput than Transformers) and linear scaling in sequence length, and its performance improves on real data up to million-length sequences. As a general sequence model backbone, Mamba achieves state- of-the-art performance across several modalities such as language, audio, and genomics. On language modeling, our Mamba-3B model outperforms Transformers of the same size and matches Transformers twice its size, both in pretraining and downstream evaluation. Subjects: Machine Learning (cs.LG); Artificial Intelligence (cs.AI) Cite as: arXiv:2312.00752 [cs.LG] (or arXiv:2312.00752v2 [cs.LG] for this version) https://doi.org/10.48550/arXiv.2312.00752 Focus to learn more arXiv-issued DOI via DataCite Submission history From: Albert Gu [view email] [v1] Fri, 1 Dec 2023 18:01:34 UTC (1,264 KB) [v2] Fri, 31 May 2024 17:55:27 UTC (1,017 KB) Full-text links: Access Paper:   View PDF   HTML (experimental)   TeX Source [image] view license Current browse context: cs.LG < prev | next > new | recent | 2023-12 Change to browse by: cs cs.AI References & Citations   NASA ADS   Google Scholar   Semantic Scholar 2 blog links (what is this?) export BibTeX citation BibTeX formatted citation   loading... Data provided by: Bookmark [image] [image]   Bibliographic Tools Bibliographic and Citation Tools   Bibliographic Explorer Toggle Bibliographic Explorer (What is the Explorer?)   Connected Papers Toggle Connected Papers (What is Connected Papers?)   Litmaps Toggle Litmaps (What is Litmaps?)   scite.ai Toggle scite Smart Citations (What are Smart Citations?)   Code, Data, Media Code, Data and Media Associated with this Article   alphaXiv Toggle alphaXiv (What is alphaXiv?)   Links to Code Toggle CatalyzeX Code Finder for Papers (What is CatalyzeX?)   DagsHub Toggle DagsHub (What is DagsHub?)   GotitPub Toggle Gotit.pub (What is GotitPub?)   Huggingface Toggle Hugging Face (What is Huggingface?)   ScienceCast Toggle ScienceCast (What is ScienceCast?)   Demos Demos   Replicate Toggle Replicate (What is Replicate?)   Spaces Toggle Hugging Face Spaces (What is Spaces?)   Spaces Toggle TXYZ.AI (What is TXYZ.AI?)   Related Papers Recommenders and Search Tools   Link to Influence Flower Influence Flower (What are Influence Flowers?)   Core recommender toggle CORE Recommender (What is CORE?)   IArxiv recommender toggle IArxiv Recommender (What is IArxiv?)   About arXivLabs arXivLabs: experimental projects with community collaborators arXivLabs is a framework that allows collaborators to develop and share new arXiv features directly on our website. Both individuals and organizations that work with arXivLabs have embraced and accepted our values of openness, community, excellence, and user data privacy. arXiv is committed to these values and only works with partners that adhere to them. Have an idea for a project that will add value for arXiv's community? Learn more about arXivLabs. Which authors of this paper are endorsers? | Disable MathJax (What is MathJax?) We gratefully acknowledge support from our major funders, member institutions , and all contributors. About   Help   Contact   Subscribe   Copyright   Privacy   Accessibility   Operational Status (opens in new tab) Major funding support from [image] [image] [image]"}

In [33]:
!pip -q install langchain-text-splitters

In [34]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [35]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=150
)

In [36]:
chunks = []

for doc in documents:

    text_chunks = splitter.split_text(doc["text"])

    for i, chunk in enumerate(text_chunks):

        chunks.append({
            "chunk_id": f"{doc['paper_id']}_chunk_{i}",
            "paper_id": doc["paper_id"],
            "title": doc["title"],
            "authors": doc["authors"],
            "year": doc["year"],
            "debate_topic": doc["debate_topic"],
            "method": doc["method"],
            "source": doc["source"],
            "text": chunk
        })

print("Total chunks:", len(chunks))

Total chunks: 358

In [37]:
for i in range(3):
    print("\n--- CHUNK", i, "---")
    print(chunks[i]["text"][:500])

--- CHUNK 0 ---
Skip to main content [image] Search Submit Donate Log in Search arXiv Press Enter to search   Advanced search Computer Science > Machine Learning arXiv:2312.00752 (cs) [Submitted on 1 Dec 2023 (v1), last revised 31 May 2024 (this version, v2)] Title:Mamba: Linear-Time Sequence Modeling with Selective State Spaces Authors:Albert Gu, Tri Dao View PDF HTML (experimental) Abstract:Foundation models, now powering most of the exciting applications in deep learning, are almost universally based on the

--- CHUNK 1 ---
modalities such as language. We identify that a key weakness of such models is their inability to perform content-based reasoning, and make several improvements. First, simply letting the SSM parameters be functions of the input addresses their weakness with discrete modalities, allowing the model to selectively propagate or forget information along the sequence length dimension depending on the current token. Second, even though this change prevents the use of efficient convolutions, we design

--- CHUNK 2 ---
up to million-length sequences. As a general sequence model backbone, Mamba achieves state- of-the-art performance across several modalities such as language, audio, and genomics. On language modeling, our Mamba-3B model outperforms Transformers of the same size and matches Transformers twice its size, both in pretraining and downstream evaluation. Subjects: Machine Learning (cs.LG); Artificial Intelligence (cs.AI) Cite as: arXiv:2312.00752 [cs.LG] (or arXiv:2312.00752v2 [cs.LG] for this version

In [38]:
import json
import os

os.makedirs("papers_chunks", exist_ok=True)

with open("papers_chunks/chunks.json", "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False, indent=2)

print("Chunks saved successfully")

Chunks saved successfully

In [39]:
print("Total chunks:", len(chunks))

Total chunks: 358

In [41]:
!pip -q install sentence-transformers

In [42]:
from sentence_transformers import SentenceTransformer

In [43]:
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [45]:
chunk_texts = [chunk["text"] for chunk in chunks]

print("Number of texts:", len(chunk_texts))

Number of texts: 358

In [46]:
embeddings = model.encode(
    chunk_texts,
    show_progress_bar=True,
    batch_size=32
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/12 [00:00<?, ?it/s]

Embedding shape: (358, 384)

In [47]:
import numpy as np

np.save(
    "papers_chunks/embeddings.npy",
    embeddings
)

print("Embeddings saved successfully")

Embeddings saved successfully

In [48]:
with open("papers_chunks/chunks_metadata.json", "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False, indent=2)

print("Metadata saved successfully")

Metadata saved successfully

In [49]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

query = "How do Transformers handle long sequence modeling?"

query_embedding = model.encode([query])

similarities = cosine_similarity(
    query_embedding,
    embeddings
)[0]

top_k = 5
top_indices = np.argsort(similarities)[::-1][:top_k]

print("Top results:\n")

for rank, idx in enumerate(top_indices, 1):
    print(f"\n--- Result {rank} ---")
    print("Similarity:", similarities[idx])
    print("Paper:", chunks[idx]["title"])
    print("Chunk ID:", chunks[idx]["chunk_id"])
    print("Text:", chunks[idx]["text"][:700])

Top results:


--- Result 1 ---
Similarity: 0.61891365
Paper: Efficiently Modeling Long Sequences with Structured State Spaces
Chunk ID: P016_chunk_0
Text: Skip to main content [image] Search Submit Donate Log in Search arXiv Press Enter to search   Advanced search Computer Science > Machine Learning arXiv:2111.00396 (cs) [Submitted on 31 Oct 2021 (v1), last revised 5 Aug 2022 (this version, v3)] Title:Efficiently Modeling Long Sequences with Structured State Spaces Authors:Albert Gu, Karan Goel, Christopher R  View PDF HTML (experimental) Abstract:A central goal of sequence modeling is designing a single principled model that can address sequence data across a range of modalities and tasks, particularly on long-range dependencies. Although conventional models including RNNs, CNNs, and Transformers have specialized variants for capturing long d

--- Result 2 ---
Similarity: 0.5953244
Paper: RecurrentGemma: Moving Past Transformers with a Hybrid Architecture
Chunk ID: P037_chunk_0
Text: Skip to main content [image] Search Submit Donate Log in Search arXiv Press Enter to search   Advanced search Computer Science > Machine Learning arXiv:2404.07839 (cs) [Submitted on 11 Apr 2024 (v1), last revised 28 Aug 2024 (this version, v2)] Title:RecurrentGemma: Moving Past Transformers for Efficient Open Language Models Authors:Aleksandar Botev, Soham De, Samuel L Smith, Anushan Fernando, George-Cristian Muraru, Ruba Haroun, Leonard Berrada, Razvan Pascanu, Pier Giuseppe Sessa, Robert Dadashi, L onard Hussenot, Johan Ferret, Sertan Girgin, Olivier Bachem, Alek Andreev, Kathleen Kenealy, Thomas Mesnard, Cassidy Hardin, Surya Bhupatiraju, Shreya Pathak, Laurent Sifre, Morgane Rivi re, Mih

--- Result 3 ---
Similarity: 0.5772705
Paper: Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention
Chunk ID: P012_chunk_1
Text: to $\mathcal{O}\left(N\right)$, where $N$ is the sequence length. We show that this formulation permits an iterative implementation that dramatically accelerates autoregressive transformers and reveals their relationship to recurrent neural networks. Our linear transformers achieve similar performance to vanilla transformers and they are up to 4000x faster on autoregressive prediction of very long sequences. Comments: ICML 2020, project at this https URL Subjects: Machine Learning (cs.LG); Machine Learning (stat.ML) Cite as: arXiv:2006.16236 [cs.LG] (or arXiv:2006.16236v3 [cs.LG] for this version) https://doi.org/10.48550/arXiv.2006.16236 Focus to learn more arXiv-issued DOI via DataCite Sub

--- Result 4 ---
Similarity: 0.55828214
Paper: Reformer: The Efficient Transformer
Chunk ID: P014_chunk_0
Text: Skip to main content [image] Search Submit Donate Log in Search arXiv Press Enter to search   Advanced search Computer Science > Machine Learning arXiv:2001.04451 (cs) [Submitted on 13 Jan 2020 (v1), last revised 18 Feb 2020 (this version, v2)] Title:Reformer: The Efficient Transformer Authors:Nikita Kitaev,  ukasz Kaiser, Anselm Levskaya View PDF HTML (experimental) Abstract:Large Transformer models routinely achieve state-of-the-art results on a number of tasks but training these models can be prohibitively costly, especially on long sequences. We introduce two techniques to improve the efficiency of Transformers. For one, we replace dot-product attention by one that uses locality-sensitiv

--- Result 5 ---
Similarity: 0.5546292
Paper: Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention
Chunk ID: P012_chunk_0
Text: Skip to main content [image] Search Submit Donate Log in Search arXiv Press Enter to search   Advanced search Computer Science > Machine Learning arXiv:2006.16236 (cs) [Submitted on 29 Jun 2020 (v1), last revised 31 Aug 2020 (this version, v3)] Title:Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention Authors:Angelos Katharopoulos, Apoorv Vyas, Nikolaos Pappas, Fran ois Fleuret View PDF HTML (experimental) Abstract:Transformers achieve remarkable performance in several tasks but due to their quadratic complexity, with respect to the input's length, they are prohibitively slow for very long sequences. To address this limitation, we express the self-attention as a lin